services:
  byondstudiomain:
    image: byondstudiomain
    build:
      context: Byondstudio-main/frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
